<template>
  <div>
    <ComponentHeader />
    <section
    id="speakers-section"
    class="speakers-section section"
    style="margin-top: 100px"
  >
    <div class="container">
      <h3 class="section-heading text-center mb-3">
        HOTELS & APARTMENTS IN KIGALI
      </h3>
      <div class="row">
        <Hotel
          v-for="(speaker, key) in speakers"
          :key="key"
          :image="speaker.image"
          :name="speaker.name"
          :contact="speaker.contact"
          :site="speaker.site"
          :location="speaker.location"
          :distanceA="speaker.distanceA"
          :distanceB="speaker.distanceB"
          :link="speaker.link"
        />
      </div>
    </div>
  </section>
  </div>
</template>

<script>
import Hotel from "../components/items/Hotel.vue";
import ComponentHeader from '../components/ComponentHeader.vue'
export default {
  components: {
    Hotel,
    ComponentHeader
  },
  data() {
    return {
      speakers: [
        {
          image: "assets/images/hotels/radisson.jpeg",
          name: "Radisson Blu",
          contact: "+250 252 252 252",
          site: "info.kigali@radissonblu.com/",
          location: "KG 2 Round-about, Kigali",
          distanceA: "5km",
          distanceB: "0 km",
          link: "https://www.radissonblu.com",
        },
        {
          image: "assets/images/hotels/marriot.jpeg",
          name: "Marriott Kigali",
          contact: "(+250) 222111111",
          site: "info.kigali@marriott.com",
          location: "A. KN 3 Ave, Nyarugenge District",
          distanceA: "10km",
          distanceB: "5km",
          link: "",
        },
        {
          image: "assets/images/hotels/serena.jpeg",
          name: "Kigali Serena Hotel",
          contact: "T. (+250) 597 100 /+250788 184 500",
          site: "kigalireservations@serena.co.rw",
          location: "A. Boulevard de la Révolution",
          distanceA: "10km",
          distanceB: "5km",
          link: "",
        },
        {
          image: "assets/images/hotels/sheraton.jpg",
          name: "4 points by Sher-aton",
          contact: "+250788 315 207",
          site: "",
          location: "KN 3 Avenue, Kigali",
          distanceB: "10km",
          distanceA: "5km",
          link: "",
        },
        {
          image: "assets/images/hotels/manor.jpg",
          name: "The Manor Hotel",
          contact: "+250786654435",
          site: "info@themanorrwanda.com",
          location: "KG 552 St, Nyarutarama",
          distanceA: "5Km",
          distanceB: "1Km",
          link: "https://www.themanorrwanda.com",
        },
        {
          image: "assets/images/hotels/lemigo.jpeg",
          name: "Lemigo Hotel",
          contact: "+250784040924",
          site: "info@lemigohotel.com",
          location: "KG 624 St, Kigali",
          distanceA: "5Km",
          distanceB: "300m",
          link: "https://www.lemigohotel.com",
        },
        {
          image: "assets/images/hotels/gorilla.jpg",
          name: "Gorillas Golf Hotel",
          contact: "+250788174000",
          site: "reservation@gorillashotels.com",
          location: "KG 9 Avenue | KG 274 Street | Nyarutarama",
          distanceA: "5km",
          distanceB: "500m",
          link: "https://www.gorillashotels.com",
        },
        {
          image: "assets/images/hotels/lando.jpeg",
          name: "Hotel Chez Lando",
          contact: "+250 788385300",
          site: "info@chezlando.com",
          location: "KG 201st , Airport Road",
          distanceA: "3km",
          distanceB: "1Km",
          link: "https://www.chezlando.com",
        },
        {
          image: "assets/images/hotels/jour.jpg",
          name: "Beau Sejour Hotel Kigali",
          contact: "+250788388885",
          site: "info@beausejourhotel.rw/",
          location: "KG 201st , Airport Road",
          distanceA: "3km",
          distanceB: "1Km",
          link: "https://www.beausejourhotel.rw",
        },
        {
          image: "assets/images/hotels/grazia.jpeg",
          name: "Grazia Apartments Hote",
          contact: "+250788862351",
          site: "graziaparts@gmail.com",
          location: "KG 624 stKigali",
          distanceA: "5km",
          distanceB: "300m",
          link: "https://www.graziaapartments.com",
        },
        {
          image: "assets/images/hotels/diplomat.jpeg",
          name: "Kigali Diplomat Hotel",
          contact: "+250782083001",
          site: "info@kigalidiplomathotel.com",
          location: "2 KG 566 St,Kigali",
          distanceA: "5km",
          distanceB: "100m",
          link: "https://www.kigalidiplomathotel.com",
        },
        {
          image: "assets/images/hotels/accord.jpeg",
          name: "Accord Hotel",
          contact: "+250783419977",
          site: "",
          location: "KG628 Street",
          distanceA: "5Km",
          distanceB: "300m",
          link: "https://www.accordhotel.rw",
        },
        {
          image: "assets/images/hotels/boutique.jpeg",
          name: "the Court boutique Hotel",
          contact: "+250787065050",
          site: "reservations@thecourtboutiquehotel.com",
          location: "KG628 ST The Court , Kigali",
          distanceA: "5Km",
          distanceB: "300m",
          link: "",
        },
        {
          image: "assets/images/hotels/grand.jpeg",
          name: "Grand Legacy Hotel",
          contact: "+250788303483",
          site: "info@grandlegacy.rw",
          location: "KN 3 Rd, Kigali, Rwanda",
          distanceA: "4Km",
          distanceB: "1km",
          link: "",
        },
        {
          image: "assets/images/hotels/green.jpeg",
          name: "The Greenwich Hotel",
          contact: "+250785993670",
          site: "info@rwandagreenwichhotel.com",
          location: "KG 201st , Airport Road",
          distanceA: "3Km",
          distanceB: "1km",
          link: "",
        },
        {
          image: "assets/images/hotels/blue.jpeg",
          name: "Blueberry Hotel",
          contact: "+250788398000",
          site: "blueberryrw@gmail.com",
          location: "KG 9 Avenue 79 MTN ROAD , NYARUTARAMA, Kigali, Rwanda",
          distanceA: "6Km",
          distanceB: "2km",
          link: "",
        },
        {
          image: "assets/images/hotels/CityBlue.jpeg",
          name: "CityBlue Hotel & Suites Embassy Row",
          contact: "+250786999999",
          site: "reservations@citybluehotels.com",
          location: "KG 7 Ave, Kigali,",
          distanceA: "6Km",
          distanceB: "1Km",
          link: "",
        },
        {
          image: "assets/images/hotels/royale.jpeg",
          name: "Le Royale Apartments",
          contact: "+250782265965",
          site: "rent@leroyale.rw",
          location: "Nyarutarama",
          distanceA: "4.5 km",
          distanceB: "0.5km",
          link: "",
        },
        {
          image: "assets/images/hotels/CROWN.jpg",
          name: "CROWN Conference Hall",
          contact: "+250788331440",
          site: "reservations@crownconferencerwanda.com",
          location: "KG 13 AVENUE 20 NYARU-TARAMA KIGALI RWANDA",
          distanceA: "4.5 km",
          distanceB: "0.5km",
          link: "",
        },
        {
          image: "assets/images/hotels/White.jpeg",
          name: "White Stone Apartments",
          contact: "+250788380101",
          site: "info@wsapartment.com/ bookings@wsapartment.com;",
          location: "KG 552 Street, Kigali/Nyarutarama",
          distanceA: "7km",
          distanceB: "2km",
          link: "",
        },
        {
          image: "assets/images/hotels/cannan.jpeg",
          name: "Canaan Golf Apartments",
          contact: "+250780360510",
          site: "info@canaanapartments",
          location: "KG 552 Street, Kigali Kigali/ Nyarutarama",
          distanceA: "7.2km",
          distanceB: "2.3km",
          link: "",
        },
        {
          image: "assets/images/hotels/MilleCollines.jpeg",
          name: "Hotel des Mille Collines",
          contact: "+250 788 192 530",
          site: "reservations@millecollines.rw",
          location: "2KN 6th Avenue PO Box 1322 Kigali/Kiyovu",
          distanceA: "9km",
          distanceB: "4km",
          link: "",
        },
        {
          image: "assets/images/hotels/Ubumwe.jpg",
          name: "Ubumwe Grande Hotel",
          contact: "+250 783 744 755",
          site: "reservations@theapdl.com",
          location: "Kigali/Kiyovu",
          distanceA: "9km",
          distanceB: "4km",
          link: "",
        },
        {
          image: "assets/images/hotels/hotel-villa-portofino.jpg",
          name: "Villa Portofino Hotel",
          contact: "+250 252 500 555",
          site: "info@hotelvillaortofinokigali.com",
          location: "119 KG 9 Avenue, Nyarutarama, Kigali",
          distanceA: "7km",
          distanceB: "2.3km",
          link: "",
        },
        {
          image: "assets/images/hotels/onomo.jpeg",
          name: "Onomo Hotel",
          contact: "+250 252 554700",
          site: "reservations.kigali@onomohotel.com",
          location: "KN 1 Avenue, Rugenge, Nyarugenge",
          distanceA: "7.8km",
          distanceB: "3.6km",
          link: "",
        },
        {
          image: "assets/images/hotels/Park.jpeg",
          name: "Park Inn by Radisson",
          contact: "+250 788 132 500",
          site: "info.kigali@rezidorparkinn.com",
          location: "c/o Avenue de Kiyovu and Rues des parcs",
          distanceA: "8.5km",
          distanceB: "3.4km",
          link: "",
        },
        {
          image: "assets/images/hotels/Elevate.jpg",
          name: "Elevate suites",
          contact: "+2502550180816 / +250 782 002 220",
          site: "info@elevatesuites.com,",
          location: "KG 13 avenue, No.88, Nyarutarama, Kigali",
          distanceA: "7km",
          distanceB: "2km",
          link: "",
        },
        {
          image: "assets/images/hotels/galaxy.jpeg",
          name: "Galaxy Hotel",
          contact: "+ 250 252 500230",
          site: "reservations@ galaxyhotelrwanda.com",
          location: "KN 25 St. 7, Kiyovu Kigali",
          distanceA: "9km",
          distanceB: "4km",
          link: "",
        },
        {
          image: "assets/images/hotels/Great.jpg",
          name: "Great Season Hotel",
          contact: "+250 783 814 000",
          site: "info@greatseasonshotel.rw",
          location: "KG 422 Street House No. 2, Kigali, Gacuriro",
          distanceA: "9km",
          distanceB: "4km",
          link: "",
        },
        {
          image: "assets/images/hotels/hill.jpeg",
          name: "Hill view Hotel",
          contact: "+250 783 462 500 / (+250) 252 576 642",
          site: "info@hillviewhotelrwanda. com",
          location: "KN25 St Kiyovu/Kigali",
          distanceA: "8.5km",
          distanceB: "3.5km",
          link: "",
        },
        {
          image: "assets/images/hotels/Stfamille.jpeg",
          name: "Sainte Famille Hotel",
          contact: "0784 180 076",
          site: "reservation@saintefamillehotel.com",
          location: "1 KN 1 St, Kigali",
          distanceA: "8.5km",
          distanceB: "4km",
          link: "",
        },
        {
          image: "assets/images/hotels/kalisimbi.jpeg",
          name: "Karisimbi Hotel",
          contact: "+250 788 517 073",
          site: "info@hotelkarisimbi.com",
          location: "KN41, Bigogwe Road, Kiyovu Street, Kigali",
          distanceA: "8km",
          distanceB: "4km",
          link: "",
        },
        {
          image: "assets/images/hotels/TheRetreat.jpeg",
          name: "The Retreat by Heaven",
          contact: "+250 782 000 001",
          site: "theretreat@heavenrwanda. com",
          location: "KN5 Road, Kigali/Kiyovu",
          distanceA: "8.5km",
          distanceB: "3.4km",
          link: "",
        },
        {
          image: "assets/images/hotels/Mythos.jpg",
          name: "Mythos Boutique",
          contact: "+250 787 838 564",
          site: "info@mythos.rw",
          location: "KN 50, Kiyouvu/Kigali",
          distanceA: "8km",
          distanceB: "4km",
          link: "",
        },
        {
          image: "assets/images/hotels/StippHotel.jpeg",
          name: "Stipp Hotel",
          contact: "+252500275 / +252500277",
          site: "www.stipphotelrwanda.com",
          location: "KN 54 St, Kigali/Kiyovu",
          distanceA: "8km",
          distanceB: "3.5km",
          link: "",
        },
        {
          image: "assets/images/hotels/TheMirror.jpeg",
          name: "The Mirror Hotel",
          contact: "+250 783705716 / +250735523321",
          site: "info@themirrorwanda.com / themirrohotel@gmail.com",
          location: "KN 5 Rd, Kigali",
          distanceA: "3km",
          distanceB: "3km",
          link: "",
        },
        {
          image: "assets/images/hotels/Urban.jpg",
          name: "Urban city blue",
          contact: "+250 7878 11111/+250 7878 22222/+250786999999",
          site: "reservations@citybluehotels. com",
          location: "KN 51 St, Kigali",
          distanceA: "8.2km",
          distanceB: "3.1km",
          link: "",
        },
        {
          image: "assets/images/hotels/Quiet.jpeg",
          name: "Quiet Haven Hotel",
          contact: "0786 689 763",
          site: "info@quiethavenhotel.com",
          location: "62 KG 9 Ave, Kigali/ Nyarutarama",
          distanceA: "6.2km",
          distanceB: "2.5km",
          link: "",
        },
        {
          image: "assets/images/hotels/Rose.jpg",
          name: "Rose Garden Hotel",
          contact: "0733 888 899",
          site: "rosegarden@homartgroup.com",
          location: "No.87, KG 9 Avenue, Nyarutarama, Gasabo, Kigali",
          distanceA: "6.4km",
          distanceB: "2.7km",
          link: "",
        },
        {
          image: "assets/images/hotels/M.jpeg",
          name: "M Hotel",
          contact: "0789 999 999",
          site: "reservation@mhotelkigali.com",
          location: "KN1 Ave, Kigali",
          distanceA: "7.7km",
          distanceB: "3.5km",
          link: "",
        },
      ],
    };
  },
};
</script>